server:
  port: 8080
spring:
  lbserviceDataSource:
    druid:
      url: jdbc:mysql://192.168.2.41:3306/lbservice?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: root
      password: richardsun
      type: com.alibaba.druid.pool.DruidDataSource
