
spring:
  lbserviceDataSource:
    druid:
      url: jdbc:mysql://192.168.2.16:33306/lbservice?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: hr
      password: E1opTTYV8QZ9U
      type: com.alibaba.druid.pool.DruidDataSource
  mail:
      host: smtp.exmail.qq.com
      username: hr@lebbay.com
      password: Lebbay2019
      protocol: smtp
      properties:
        mail:
          smtp: auth
          port: 465
          socketFactory:
            port: 465
            fallback: false
            class: javax.net.ssl.SSLSocketFactory
      default-encoding: utf-8
      from: hr@lebbay.com
      transport:
        protocol: smtp
#日志级别
logging:
    level: info
#简历解析账号密码
jianlijiexi_username: dTEwMDIyMQ==
jianlijiexi_pwd: c3psYjIwMTkwNjE0
#ftp 配置
fileUrl: 192.168.2.41:20
ftpIp: 192.168.2.41
ftpPort: 21
ftpUserName: up
ftpPassword: 123456

configEnv: online