server:
  port: 8080
spring:
  lbserviceDataSource:
    druid:
      url: jdbc:mysql://192.168.2.41:3306/lbservice?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: root
      password: richardsun
      type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.exmail.qq.com
    username: hr@lebbay.com
    password: Lebbay2019
    protocol: smtp
    properties:
      mail:
        smtp: auth
        port: 465
        socketFactory:
          port: 465
          fallback: false
          class: javax.net.ssl.SSLSocketFactory
    default-encoding: utf-8
    from: hr@lebbay.com
    transport:
      protocol: smtp





jianlijiexi_username: dTEwMDA0OQ==
jianlijiexi_pwd: dGVzdDAyMjY=




